baseurl = "https://stjl.github.io/"
defaultContentLanguage = "zh"
locale = "zh-TW"
title = "小麟‘s blog"
theme = "dream"

[languages]
  [languages.zh]
    languageName = "中文"
    contentDir = "content/zh"
    weight = 1
  [languages.en]
    languageName = "English"
    contentDir = "content/en"
    weight = 2

[languages.en.params]
  description = "My Hugo Blog in English"

[languages.zh.params]
  description = "我的 Hugo 部落格"

# [services]
# [services.disqus]
# shortname = ""
[services.googleAnalytics]
ID = "G-XLWVSBGEG0"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
# zenMode = true

lightTheme = "emerald"
darkTheme = "forest"

# backgroundImage = "img/global-background.jpg"
# backgroundImageDark = ""

author = "stJL"
# avatar = "img/avatar.png"
headerTitle = "小麟‘s blog"
motto = "追尋星辰的漫長之旅，始於傾聽內心跳動的那一刻。"

# footerBottomText = ""

rss = true

utterancesRepo = "stJL/stjl.github.io"

# valine = true
# LEANCLOUD_APP_ID = ""
# LEANCLOUD_APP_KEY = ""

# waline = true
# walineServer = ""

# email = ""

siteStartYear = 2026

favicon = "favicon.ico"

# Syntax highlighting
# customSyntaxHighlighting = true

# options
# stickyNav = true
reorderNavItems = ["github", "about", "search", "rss", "posts", "categories", "tags", "series"]
collapseNavItems = ["posts", "categories", "tags"]
# noDefaultSummaryCover = true
showTableOfContents = true
showSummaryCoverInPost = true
imageZoomableInPost = true
showPrevNextPost = true
# reorderShares = ["x", "facebook", "whatsapp"]

[params.navItems]
# series = { href = "/series", icon = "planet", title = "Series" }
github = { href = "https://github.com/stJL", target = "_blank", icon = "logo-github", title = "GitHub" }

# [params.twikoo]
# enabled = true
# envID = ""
# region = ""
# lang = ""

[params.advanced]
customCSS = ["css/custom.css"]
# customJS = ["js/custom.js"]

# [params.experimental]
# jsDate = true
# jsDateFormat = "yyyy年MM月dd日"
